const fs = require('fs');
const path = require('path');
const REPO_ROOT = path.resolve('D:/nomadas-tour');
const filePath = path.join(REPO_ROOT, 'components/branding/AgencyBrandingProvider.tsx');
const src = fs.readFileSync(filePath, 'utf8');
const expected = "import { buildAgencyBrandingStyle, type BrandingStyle } from '@/lib/brand/utils'";
console.log('File exists:', fs.existsSync(filePath));
console.log('Contains expected:', src.includes(expected));
console.log('Expected:', expected);
console.log('Actual line:', src.split('\n').find(l => l.includes('buildAgencyBrandingStyle')));